// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7VXDCVTdZ5eeLitChDpTi1GpLa03ovNw',
    appId: '1:118273982518:web:8c88a2ba2581a04841d897',
    messagingSenderId: '118273982518',
    projectId: 'smart-home-lamp-d68de',
    authDomain: 'smart-home-lamp-d68de.firebaseapp.com',
    databaseURL: 'https://smart-home-lamp-d68de-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-lamp-d68de.firebasestorage.app',
    measurementId: 'G-Z6HSQS5QW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn5MauTbTWzAqUBn8z64FqgEAQqr6QT68',
    appId: '1:118273982518:android:c99324de94e08f9841d897',
    messagingSenderId: '118273982518',
    projectId: 'smart-home-lamp-d68de',
    databaseURL: 'https://smart-home-lamp-d68de-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-lamp-d68de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPifTtnZIu-ddNko3H9bupigH7La5Gwlw',
    appId: '1:118273982518:ios:4f13086e1acc5eb441d897',
    messagingSenderId: '118273982518',
    projectId: 'smart-home-lamp-d68de',
    databaseURL: 'https://smart-home-lamp-d68de-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-lamp-d68de.firebasestorage.app',
    iosBundleId: 'com.example.lumenApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPifTtnZIu-ddNko3H9bupigH7La5Gwlw',
    appId: '1:118273982518:ios:4f13086e1acc5eb441d897',
    messagingSenderId: '118273982518',
    projectId: 'smart-home-lamp-d68de',
    databaseURL: 'https://smart-home-lamp-d68de-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-lamp-d68de.firebasestorage.app',
    iosBundleId: 'com.example.lumenApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7VXDCVTdZ5eeLitChDpTi1GpLa03ovNw',
    appId: '1:118273982518:web:57e4461c5fa9e63b41d897',
    messagingSenderId: '118273982518',
    projectId: 'smart-home-lamp-d68de',
    authDomain: 'smart-home-lamp-d68de.firebaseapp.com',
    databaseURL: 'https://smart-home-lamp-d68de-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-lamp-d68de.firebasestorage.app',
    measurementId: 'G-3CZY86PCM3',
  );

}